### PR TITLE
Interactomes in mitab format

### PR DESCRIPTION
**Pull request by jmedinaebi**
Main change, apart form the new button, is the style of the buttons. Compare https://intact-portal.github.io/intact-portal-view/interactomes and https://intact-portal.github.io/intact-portal-view/interactomes

### CODE REVIEW

**Comment by EliotRagueneau** [comment]
You pasted twice the same link. I assume you meant to compare it with the live version?

**Comment by EliotRagueneau** [comment]
The former team of designer agreed to restrict rounded corner usage to the filters. While I do like them, I think here it's a bit too much. 

I would recommend to use 
```
<div class="button-group rounded">
  ... class="button"
</div>
```

Indeed this class allows to create a neat grouping of buttons where only the first and last buttons are rounded

**Comment by jmedinaebi** [comment]
> The former team of designer agreed to restrict rounded corner usage to the filters. While I do like them, I think here it's a bit too much.
> 
> I would recommend to use
> 
> ```
> <div class="button-group rounded">
>   ... class="button"
> </div>
> ```
> 
> Indeed this class allows to create a neat grouping of buttons where only the first and last buttons are rounded

I like it how it looks with that
Screenshot 2024-10-11 at 13 12 48
 But if the window is smaller and all 3 buttons don't fit together, then it looks weird
Screenshot 2024-10-11 at 13 12 58

**Comment by jmedinaebi** [comment]
@EliotRagueneau I fixed the issue I mentioned before, now the 3 buttons stay on the same row. I also updated the icon for Schizosaccharomyces pombe, as we did for Complex Portal recently.

**Comment by EliotRagueneau** [comment]
Perfect! Thanks a lot :D

**Pull request merged**
